// Code generated by options-gen v0.55.3. DO NOT EDIT.

package workerpool

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"github.com/metalagman/appkit/logger"
)

type Option func(o *Options)

func NewOptions(
	options ...Option,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

// WithLogger sets the logger used by the pool and its workers.
func WithLogger(opt logger.Logger) Option {
	return func(o *Options) { o.logger = opt }
}

// WithNumWorkers sets the number of worker goroutines to start.
func WithNumWorkers(opt int) Option {
	return func(o *Options) { o.numWorkers = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("numWorkers", _validate_Options_numWorkers(o)))
	return errs.AsError()
}

func _validate_Options_numWorkers(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.numWorkers, "min=2"); err != nil {
		return fmt461e464ebed9.Errorf("field `numWorkers` did not pass the test: %w", err)
	}
	return nil
}
